server:
  port: ${PORT:8480}
tomcat:
  ajp:
    port: 8488
    remoteauthentication: false
    enabled: true
---
spring:
    profiles: dev
server:
    port: ${PORT:8421}
tomcat:
  ajp:
    port: 8488
    remoteauthentication: false
    enabled: true
---
spring:
    profiles: real
server:
    port: ${PORT:8421}
tomcat:
  ajp:
    port: 8488
    remoteauthentication: false
    enabled: true