# -- Server Port
server:
  port: ${PORT:8761}
    
# -- Eureka
eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 60000
    response-cache-update-interval-ms: 3000
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false